// <auto-generated />
using System;
using Insurance.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Insurance.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDBFactory))]
    partial class ApplicationDBFactoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.ConstructionType", b =>
                {
                    b.Property<int>("ConstructionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConstructionTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConstructionTypeId");

                    b.ToTable("ConstructionTypes", (string)null);

                    b.HasData(
                        new
                        {
                            ConstructionTypeId = 1,
                            Name = "RCC (Reinforced Cement Concrete)"
                        },
                        new
                        {
                            ConstructionTypeId = 2,
                            Name = "Brick & Cement"
                        },
                        new
                        {
                            ConstructionTypeId = 3,
                            Name = "Stone & Mud"
                        },
                        new
                        {
                            ConstructionTypeId = 4,
                            Name = "Wooden Frame"
                        },
                        new
                        {
                            ConstructionTypeId = 5,
                            Name = "Steel Frame"
                        },
                        new
                        {
                            ConstructionTypeId = 6,
                            Name = "Bamboo/Thatch"
                        });
                });

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Districts", (string)null);

                    b.HasData(
                        new
                        {
                            DistrictId = 1,
                            Name = "Taplejung",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 2,
                            Name = "Panchthar",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 3,
                            Name = "Ilam",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 4,
                            Name = "Jhapa",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 5,
                            Name = "Morang",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 6,
                            Name = "Sunsari",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 7,
                            Name = "Dhankuta",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 8,
                            Name = "Terhathum",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 9,
                            Name = "Sankhuwasabha",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 10,
                            Name = "Bhojpur",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 11,
                            Name = "Solukhumbu",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 12,
                            Name = "Okhaldhunga",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 13,
                            Name = "Khotang",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 14,
                            Name = "Udayapur",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 15,
                            Name = "Saptari",
                            ProvinceId = 2
                        },
                        new
                        {
                            DistrictId = 16,
                            Name = "Siraha",
                            ProvinceId = 2
                        },
                        new
                        {
                            DistrictId = 17,
                            Name = "Dhanusha",
                            ProvinceId = 2
                        },
                        new
                        {
                            DistrictId = 18,
                            Name = "Mahottari",
                            ProvinceId = 2
                        },
                        new
                        {
                            DistrictId = 19,
                            Name = "Sarlahi",
                            ProvinceId = 2
                        },
                        new
                        {
                            DistrictId = 20,
                            Name = "Rautahat",
                            ProvinceId = 2
                        },
                        new
                        {
                            DistrictId = 21,
                            Name = "Bara",
                            ProvinceId = 2
                        },
                        new
                        {
                            DistrictId = 22,
                            Name = "Parsa",
                            ProvinceId = 2
                        },
                        new
                        {
                            DistrictId = 23,
                            Name = "Dolakha",
                            ProvinceId = 3
                        },
                        new
                        {
                            DistrictId = 24,
                            Name = "Sindhupalchok",
                            ProvinceId = 3
                        },
                        new
                        {
                            DistrictId = 25,
                            Name = "Rasuwa",
                            ProvinceId = 3
                        },
                        new
                        {
                            DistrictId = 26,
                            Name = "Dhading",
                            ProvinceId = 3
                        },
                        new
                        {
                            DistrictId = 27,
                            Name = "Nuwakot",
                            ProvinceId = 3
                        },
                        new
                        {
                            DistrictId = 28,
                            Name = "Kathmandu",
                            ProvinceId = 3
                        },
                        new
                        {
                            DistrictId = 29,
                            Name = "Bhaktapur",
                            ProvinceId = 3
                        },
                        new
                        {
                            DistrictId = 30,
                            Name = "Lalitpur",
                            ProvinceId = 3
                        },
                        new
                        {
                            DistrictId = 31,
                            Name = "Kavrepalanchok",
                            ProvinceId = 3
                        },
                        new
                        {
                            DistrictId = 32,
                            Name = "Ramechhap",
                            ProvinceId = 3
                        },
                        new
                        {
                            DistrictId = 33,
                            Name = "Sindhuli",
                            ProvinceId = 3
                        },
                        new
                        {
                            DistrictId = 34,
                            Name = "Makwanpur",
                            ProvinceId = 3
                        },
                        new
                        {
                            DistrictId = 35,
                            Name = "Chitwan",
                            ProvinceId = 3
                        },
                        new
                        {
                            DistrictId = 36,
                            Name = "Gorkha",
                            ProvinceId = 4
                        },
                        new
                        {
                            DistrictId = 37,
                            Name = "Manang",
                            ProvinceId = 4
                        },
                        new
                        {
                            DistrictId = 38,
                            Name = "Mustang",
                            ProvinceId = 4
                        },
                        new
                        {
                            DistrictId = 39,
                            Name = "Myagdi",
                            ProvinceId = 4
                        },
                        new
                        {
                            DistrictId = 40,
                            Name = "Kaski",
                            ProvinceId = 4
                        },
                        new
                        {
                            DistrictId = 41,
                            Name = "Lamjung",
                            ProvinceId = 4
                        },
                        new
                        {
                            DistrictId = 42,
                            Name = "Tanahun",
                            ProvinceId = 4
                        },
                        new
                        {
                            DistrictId = 43,
                            Name = "Nawalpur",
                            ProvinceId = 4
                        },
                        new
                        {
                            DistrictId = 44,
                            Name = "Syangja",
                            ProvinceId = 4
                        },
                        new
                        {
                            DistrictId = 45,
                            Name = "Parbat",
                            ProvinceId = 4
                        },
                        new
                        {
                            DistrictId = 46,
                            Name = "Baglung",
                            ProvinceId = 4
                        },
                        new
                        {
                            DistrictId = 47,
                            Name = "Rukum East",
                            ProvinceId = 5
                        },
                        new
                        {
                            DistrictId = 48,
                            Name = "Rolpa",
                            ProvinceId = 5
                        },
                        new
                        {
                            DistrictId = 49,
                            Name = "Pyuthan",
                            ProvinceId = 5
                        },
                        new
                        {
                            DistrictId = 50,
                            Name = "Gulmi",
                            ProvinceId = 5
                        },
                        new
                        {
                            DistrictId = 51,
                            Name = "Arghakhanchi",
                            ProvinceId = 5
                        },
                        new
                        {
                            DistrictId = 52,
                            Name = "Palpa",
                            ProvinceId = 5
                        },
                        new
                        {
                            DistrictId = 53,
                            Name = "Nawalparasi East",
                            ProvinceId = 5
                        },
                        new
                        {
                            DistrictId = 54,
                            Name = "Rupandehi",
                            ProvinceId = 5
                        },
                        new
                        {
                            DistrictId = 55,
                            Name = "Kapilvastu",
                            ProvinceId = 5
                        },
                        new
                        {
                            DistrictId = 56,
                            Name = "Dang",
                            ProvinceId = 5
                        },
                        new
                        {
                            DistrictId = 57,
                            Name = "Banke",
                            ProvinceId = 5
                        },
                        new
                        {
                            DistrictId = 58,
                            Name = "Bardiya",
                            ProvinceId = 5
                        },
                        new
                        {
                            DistrictId = 59,
                            Name = "Dolpa",
                            ProvinceId = 6
                        },
                        new
                        {
                            DistrictId = 60,
                            Name = "Mugu",
                            ProvinceId = 6
                        },
                        new
                        {
                            DistrictId = 61,
                            Name = "Humla",
                            ProvinceId = 6
                        },
                        new
                        {
                            DistrictId = 62,
                            Name = "Jumla",
                            ProvinceId = 6
                        },
                        new
                        {
                            DistrictId = 63,
                            Name = "Kalikot",
                            ProvinceId = 6
                        },
                        new
                        {
                            DistrictId = 64,
                            Name = "Dailekh",
                            ProvinceId = 6
                        },
                        new
                        {
                            DistrictId = 65,
                            Name = "Jajarkot",
                            ProvinceId = 6
                        },
                        new
                        {
                            DistrictId = 66,
                            Name = "Rukum West",
                            ProvinceId = 6
                        },
                        new
                        {
                            DistrictId = 67,
                            Name = "Salyan",
                            ProvinceId = 6
                        },
                        new
                        {
                            DistrictId = 68,
                            Name = "Surkhet",
                            ProvinceId = 6
                        },
                        new
                        {
                            DistrictId = 69,
                            Name = "Bajura",
                            ProvinceId = 7
                        },
                        new
                        {
                            DistrictId = 70,
                            Name = "Bajhang",
                            ProvinceId = 7
                        },
                        new
                        {
                            DistrictId = 71,
                            Name = "Darchula",
                            ProvinceId = 7
                        },
                        new
                        {
                            DistrictId = 72,
                            Name = "Baitadi",
                            ProvinceId = 7
                        },
                        new
                        {
                            DistrictId = 73,
                            Name = "Dadeldhura",
                            ProvinceId = 7
                        },
                        new
                        {
                            DistrictId = 74,
                            Name = "Doti",
                            ProvinceId = 7
                        },
                        new
                        {
                            DistrictId = 75,
                            Name = "Achham",
                            ProvinceId = 7
                        },
                        new
                        {
                            DistrictId = 76,
                            Name = "Kailali",
                            ProvinceId = 7
                        },
                        new
                        {
                            DistrictId = 77,
                            Name = "Kanchanpur",
                            ProvinceId = 7
                        });
                });

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.InsuredPerson", b =>
                {
                    b.Property<int>("InsuredId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuredId"));

                    b.Property<string>("CitizenshipOrIdNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("InsuredId");

                    b.ToTable("InsuredPersons", (string)null);
                });

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.Municipality", b =>
                {
                    b.Property<int>("MunicipalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MunicipalityId"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MunicipalityId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Municipalities", (string)null);

                    b.HasData(
                        new
                        {
                            MunicipalityId = 1,
                            DistrictId = 28,
                            Name = "Kathmandu Metropolitan City"
                        },
                        new
                        {
                            MunicipalityId = 2,
                            DistrictId = 28,
                            Name = "Kirtipur Municipality"
                        },
                        new
                        {
                            MunicipalityId = 3,
                            DistrictId = 28,
                            Name = "Budhanilkantha Municipality"
                        },
                        new
                        {
                            MunicipalityId = 4,
                            DistrictId = 28,
                            Name = "Kageshwari-Manohara Municipality"
                        },
                        new
                        {
                            MunicipalityId = 5,
                            DistrictId = 28,
                            Name = "Tarakeshwar Municipality"
                        },
                        new
                        {
                            MunicipalityId = 6,
                            DistrictId = 28,
                            Name = "Nagarjun Municipality"
                        },
                        new
                        {
                            MunicipalityId = 7,
                            DistrictId = 28,
                            Name = "Shankharapur Municipality"
                        },
                        new
                        {
                            MunicipalityId = 8,
                            DistrictId = 28,
                            Name = "Gokarneshwor Municipality"
                        },
                        new
                        {
                            MunicipalityId = 9,
                            DistrictId = 28,
                            Name = "Dakshinkali Municipality"
                        },
                        new
                        {
                            MunicipalityId = 10,
                            DistrictId = 28,
                            Name = "Chandragiri Municipality"
                        },
                        new
                        {
                            MunicipalityId = 11,
                            DistrictId = 28,
                            Name = "Tokha Municipality"
                        },
                        new
                        {
                            MunicipalityId = 12,
                            DistrictId = 30,
                            Name = "Lalitpur Metropolitan City"
                        },
                        new
                        {
                            MunicipalityId = 13,
                            DistrictId = 30,
                            Name = "Mahalaxmi Municipality"
                        },
                        new
                        {
                            MunicipalityId = 14,
                            DistrictId = 30,
                            Name = "Godawari Municipality"
                        },
                        new
                        {
                            MunicipalityId = 15,
                            DistrictId = 30,
                            Name = "Bagmati Municipality"
                        },
                        new
                        {
                            MunicipalityId = 16,
                            DistrictId = 30,
                            Name = "Konjyosom Rural Municipality"
                        },
                        new
                        {
                            MunicipalityId = 17,
                            DistrictId = 29,
                            Name = "Bhaktapur Municipality"
                        },
                        new
                        {
                            MunicipalityId = 18,
                            DistrictId = 29,
                            Name = "Madhyapur Thimi Municipality"
                        },
                        new
                        {
                            MunicipalityId = 19,
                            DistrictId = 29,
                            Name = "Changunarayan Municipality"
                        },
                        new
                        {
                            MunicipalityId = 20,
                            DistrictId = 29,
                            Name = "Suryabinayak Municipality"
                        },
                        new
                        {
                            MunicipalityId = 21,
                            DistrictId = 35,
                            Name = "Bharatpur Metropolitan City"
                        },
                        new
                        {
                            MunicipalityId = 22,
                            DistrictId = 35,
                            Name = "Ratnanagar Municipality"
                        },
                        new
                        {
                            MunicipalityId = 23,
                            DistrictId = 35,
                            Name = "Madi Municipality"
                        },
                        new
                        {
                            MunicipalityId = 24,
                            DistrictId = 40,
                            Name = "Pokhara Metropolitan City"
                        },
                        new
                        {
                            MunicipalityId = 25,
                            DistrictId = 40,
                            Name = "Annapurna Rural Municipality"
                        },
                        new
                        {
                            MunicipalityId = 26,
                            DistrictId = 40,
                            Name = "Machhapuchchhre Rural Municipality"
                        },
                        new
                        {
                            MunicipalityId = 27,
                            DistrictId = 40,
                            Name = "Madi Rural Municipality"
                        },
                        new
                        {
                            MunicipalityId = 28,
                            DistrictId = 40,
                            Name = "Rupa Rural Municipality"
                        },
                        new
                        {
                            MunicipalityId = 29,
                            DistrictId = 4,
                            Name = "Bhadrapur Municipality"
                        },
                        new
                        {
                            MunicipalityId = 30,
                            DistrictId = 4,
                            Name = "Mechinagar Municipality"
                        },
                        new
                        {
                            MunicipalityId = 31,
                            DistrictId = 4,
                            Name = "Birtamod Municipality"
                        },
                        new
                        {
                            MunicipalityId = 32,
                            DistrictId = 4,
                            Name = "Damak Municipality"
                        },
                        new
                        {
                            MunicipalityId = 33,
                            DistrictId = 4,
                            Name = "Kankai Municipality"
                        },
                        new
                        {
                            MunicipalityId = 34,
                            DistrictId = 5,
                            Name = "Biratnagar Metropolitan City"
                        },
                        new
                        {
                            MunicipalityId = 35,
                            DistrictId = 5,
                            Name = "Rangeli Municipality"
                        },
                        new
                        {
                            MunicipalityId = 36,
                            DistrictId = 5,
                            Name = "Sundar Haraicha Municipality"
                        },
                        new
                        {
                            MunicipalityId = 37,
                            DistrictId = 5,
                            Name = "Letang Municipality"
                        },
                        new
                        {
                            MunicipalityId = 38,
                            DistrictId = 6,
                            Name = "Dharan Sub-Metropolitan City"
                        },
                        new
                        {
                            MunicipalityId = 39,
                            DistrictId = 6,
                            Name = "Inaruwa Municipality"
                        },
                        new
                        {
                            MunicipalityId = 40,
                            DistrictId = 6,
                            Name = "Itahari Sub-Metropolitan City"
                        },
                        new
                        {
                            MunicipalityId = 41,
                            DistrictId = 6,
                            Name = "Duhabi Municipality"
                        },
                        new
                        {
                            MunicipalityId = 42,
                            DistrictId = 54,
                            Name = "Butwal Sub-Metropolitan City"
                        },
                        new
                        {
                            MunicipalityId = 43,
                            DistrictId = 54,
                            Name = "Lumbini Sanskritik Municipality"
                        },
                        new
                        {
                            MunicipalityId = 44,
                            DistrictId = 54,
                            Name = "Devdaha Municipality"
                        },
                        new
                        {
                            MunicipalityId = 45,
                            DistrictId = 54,
                            Name = "Sainamaina Municipality"
                        },
                        new
                        {
                            MunicipalityId = 46,
                            DistrictId = 54,
                            Name = "Tilottama Municipality"
                        },
                        new
                        {
                            MunicipalityId = 47,
                            DistrictId = 57,
                            Name = "Nepalgunj Sub-Metropolitan City"
                        },
                        new
                        {
                            MunicipalityId = 48,
                            DistrictId = 57,
                            Name = "Kohalpur Municipality"
                        },
                        new
                        {
                            MunicipalityId = 49,
                            DistrictId = 57,
                            Name = "Rapti Sonari Municipality"
                        },
                        new
                        {
                            MunicipalityId = 50,
                            DistrictId = 68,
                            Name = "Birendranagar Municipality"
                        },
                        new
                        {
                            MunicipalityId = 51,
                            DistrictId = 68,
                            Name = "Gurtu Rural Municipality"
                        },
                        new
                        {
                            MunicipalityId = 52,
                            DistrictId = 76,
                            Name = "Dhangadhi Sub-Metropolitan City"
                        },
                        new
                        {
                            MunicipalityId = 53,
                            DistrictId = 76,
                            Name = "Ghodaghodi Municipality"
                        },
                        new
                        {
                            MunicipalityId = 54,
                            DistrictId = 76,
                            Name = "Tikapur Municipality"
                        },
                        new
                        {
                            MunicipalityId = 55,
                            DistrictId = 76,
                            Name = "Bhajani Municipality"
                        },
                        new
                        {
                            MunicipalityId = 56,
                            DistrictId = 77,
                            Name = "Mahendranagar Municipality"
                        },
                        new
                        {
                            MunicipalityId = 57,
                            DistrictId = 77,
                            Name = "Bedkot Municipality"
                        },
                        new
                        {
                            MunicipalityId = 58,
                            DistrictId = 77,
                            Name = "Punarbas Municipality"
                        },
                        new
                        {
                            MunicipalityId = 59,
                            DistrictId = 17,
                            Name = "Janakpur Sub-Metropolitan City"
                        },
                        new
                        {
                            MunicipalityId = 60,
                            DistrictId = 17,
                            Name = "Dhanusadham Municipality"
                        },
                        new
                        {
                            MunicipalityId = 61,
                            DistrictId = 21,
                            Name = "Kalaiya Sub-Metropolitan City"
                        },
                        new
                        {
                            MunicipalityId = 62,
                            DistrictId = 21,
                            Name = "Jitpur Simara Sub-Metropolitan City"
                        },
                        new
                        {
                            MunicipalityId = 63,
                            DistrictId = 21,
                            Name = "Mahagadhimai Municipality"
                        },
                        new
                        {
                            MunicipalityId = 64,
                            DistrictId = 22,
                            Name = "Birgunj Metropolitan City"
                        },
                        new
                        {
                            MunicipalityId = 65,
                            DistrictId = 22,
                            Name = "Bahudarmai Municipality"
                        },
                        new
                        {
                            MunicipalityId = 66,
                            DistrictId = 22,
                            Name = "Pkr Municipality"
                        });
                });

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InsuredId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PolicyEndDate")
                        .HasColumnType("date");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("PolicyStartDate")
                        .HasColumnType("date");

                    b.Property<int>("PolicyStatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("PremiumAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("RiskTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("SumInsured")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PolicyId");

                    b.HasIndex("InsuredId");

                    b.HasIndex("PolicyStatusId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RiskTypeId");

                    b.ToTable("Policies", (string)null);
                });

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.PolicyOP", b =>
                {
                    b.Property<string>("InsuredName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PremiumAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceDistrict")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("PolicyOP");

                    b.ToFunction("FGetPolicies");
                });

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.PolicyStatus", b =>
                {
                    b.Property<int>("PolicyStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PolicyStatusId");

                    b.ToTable("PolicyStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            PolicyStatusId = 1,
                            Name = "Draft"
                        },
                        new
                        {
                            PolicyStatusId = 2,
                            Name = "Active"
                        },
                        new
                        {
                            PolicyStatusId = 3,
                            Name = "Expired"
                        },
                        new
                        {
                            PolicyStatusId = 4,
                            Name = "Cancelled"
                        },
                        new
                        {
                            PolicyStatusId = 5,
                            Name = "Pending Renewal"
                        },
                        new
                        {
                            PolicyStatusId = 6,
                            Name = "Claimed"
                        },
                        new
                        {
                            PolicyStatusId = 7,
                            Name = "Suspended"
                        });
                });

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConstructionTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<byte>("NumberOfFloors")
                        .HasColumnType("tinyint");

                    b.Property<int>("PropertyTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<short>("YearBuilt")
                        .HasColumnType("smallint");

                    b.HasKey("PropertyId");

                    b.HasIndex("ConstructionTypeId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("PropertyTypeId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Properties", (string)null);
                });

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.PropertyType", b =>
                {
                    b.Property<int>("PropertyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PropertyTypeId");

                    b.ToTable("PropertyTypes", (string)null);

                    b.HasData(
                        new
                        {
                            PropertyTypeId = 1,
                            Name = "Residential"
                        },
                        new
                        {
                            PropertyTypeId = 2,
                            Name = "Commercial"
                        },
                        new
                        {
                            PropertyTypeId = 3,
                            Name = "Industrial"
                        },
                        new
                        {
                            PropertyTypeId = 4,
                            Name = "Agricultural"
                        },
                        new
                        {
                            PropertyTypeId = 5,
                            Name = "Mixed Use"
                        });
                });

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceId");

                    b.ToTable("Provinces", (string)null);

                    b.HasData(
                        new
                        {
                            ProvinceId = 1,
                            Name = "Koshi Province"
                        },
                        new
                        {
                            ProvinceId = 2,
                            Name = "Madhesh Province"
                        },
                        new
                        {
                            ProvinceId = 3,
                            Name = "Bagmati Province"
                        },
                        new
                        {
                            ProvinceId = 4,
                            Name = "Gandaki Province"
                        },
                        new
                        {
                            ProvinceId = 5,
                            Name = "Lumbini Province"
                        },
                        new
                        {
                            ProvinceId = 6,
                            Name = "Karnali Province"
                        },
                        new
                        {
                            ProvinceId = 7,
                            Name = "Sudurpashchim Province"
                        });
                });

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.RefreshToken", b =>
                {
                    b.Property<int>("Rfid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rfid"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Expiry")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RefreshToken");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Rfid");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.RiskType", b =>
                {
                    b.Property<int>("RiskTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RiskTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RiskTypeId");

                    b.ToTable("RiskTypes", (string)null);

                    b.HasData(
                        new
                        {
                            RiskTypeId = 1,
                            Name = "Fire & Allied Perils"
                        },
                        new
                        {
                            RiskTypeId = 2,
                            Name = "Earthquake"
                        },
                        new
                        {
                            RiskTypeId = 3,
                            Name = "Flood & Inundation"
                        },
                        new
                        {
                            RiskTypeId = 4,
                            Name = "Landslide"
                        },
                        new
                        {
                            RiskTypeId = 5,
                            Name = "Theft & Burglary"
                        },
                        new
                        {
                            RiskTypeId = 6,
                            Name = "Natural Disaster (Comprehensive)"
                        },
                        new
                        {
                            RiskTypeId = 7,
                            Name = "Storm & Tempest"
                        },
                        new
                        {
                            RiskTypeId = 8,
                            Name = "Impact Damage"
                        },
                        new
                        {
                            RiskTypeId = 9,
                            Name = "Riot & Strike"
                        },
                        new
                        {
                            RiskTypeId = 10,
                            Name = "All Risk"
                        });
                });

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Agent"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.District", b =>
                {
                    b.HasOne("Insurance.Domain.Entity.DbModel.Province", null)
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.Municipality", b =>
                {
                    b.HasOne("Insurance.Domain.Entity.DbModel.District", null)
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.Policy", b =>
                {
                    b.HasOne("Insurance.Domain.Entity.DbModel.InsuredPerson", null)
                        .WithMany()
                        .HasForeignKey("InsuredId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insurance.Domain.Entity.DbModel.PolicyStatus", null)
                        .WithMany()
                        .HasForeignKey("PolicyStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insurance.Domain.Entity.DbModel.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insurance.Domain.Entity.DbModel.RiskType", null)
                        .WithMany()
                        .HasForeignKey("RiskTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.Property", b =>
                {
                    b.HasOne("Insurance.Domain.Entity.DbModel.ConstructionType", null)
                        .WithMany()
                        .HasForeignKey("ConstructionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insurance.Domain.Entity.DbModel.District", null)
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insurance.Domain.Entity.DbModel.Municipality", null)
                        .WithMany()
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insurance.Domain.Entity.DbModel.PropertyType", null)
                        .WithMany()
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insurance.Domain.Entity.DbModel.Province", null)
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.RefreshToken", b =>
                {
                    b.HasOne("Insurance.Domain.Entity.DbModel.User", null)
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Insurance.Domain.Entity.DbModel.User", b =>
                {
                    b.HasOne("Insurance.Domain.Entity.DbModel.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
